apiVersion: v2
appVersion: v4.10.1
description: A Helm chart for ZITADEL
home: https://zitadel.com
icon: https://zitadel.com/zitadel-logo-dark.svg
keywords:
- identity
- oidc
- oauth
- auth
- saml
- iam
- sso
- idp
kubeVersion: '>= 1.30.0-0'
maintainers:
- email: support@zitadel.com
  name: zitadel
  url: https://zitadel.com
name: zitadel
sources:
- https://github.com/zitadel/zitadel
type: application
version: 9.24.0
