{{- if and .Values.keycloak.enabled (index .Values.keycloak "ingress" | default dict).enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "geniro.fullname" . }}-keycloak
  labels:
    {{- include "geniro.labels" . | nindent 4 }}
  {{- with .Values.keycloak.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if .Values.keycloak.ingress.className }}
  ingressClassName: {{ .Values.keycloak.ingress.className }}
  {{- end }}
  rules:
    - host: {{ .Values.keycloak.ingress.host | quote }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "geniro.fullname" . }}-keycloak
                port:
                  name: http
  {{- with .Values.keycloak.ingress.tls }}
  tls:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
